### ISSUE TITLE
Get connection error while connecting to central with multiple thread

### ISSUE THREAD

**Issue by wuwei3** [lucadruda/iotc-java-device-client#8]
Hi

I have 10 devices in central, I want to send data(temperature, humidity, CO2 etc.) to the these devices every 7 mins, I used the thread pool to send at the same time, but 

I always get this error:

com.github.lucadruda.iotc.device.exceptions.IoTCentralException: Registration error, bailing out
at com.github.lucadruda.iotc.device.DeviceProvision._internalRegister(DeviceProvision.java:138)
at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:99)
at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:73)
at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:159)
at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:153)
at com.orangelabs.iot.azure.central.IOTAzureCentralTest.utils.DeviceConnUtils.isOpen(DeviceConnUtils.java:60)
at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.reOpenConnection(PushDataThread.java:128)
at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.run(PushDataThread.java:55)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Caused by: com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceConnectionException: Exception opening connection
at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.open(ContractAPIMqtt.java:175)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.authenticateWithProvisioningService(ContractAPIMqtt.java:228)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithSasToken(RegisterTask.java:202)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithDPS(RegisterTask.java:319)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:341)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:37)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 4 more
Caused by: java.io.IOException: Unable to subscribe on topic : $dps/registrations/res/#
at com.microsoft.azure.sdk.iot.deps.transport.mqtt.MqttConnection.subscribe(MqttConnection.java:236)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.open(ContractAPIMqtt.java:170)
... 11 more
Caused by: Timed out waiting for a response from the server (32000)
at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
at com.microsoft.azure.sdk.iot.deps.transport.mqtt.MqttConnection.subscribe(MqttConnection.java:232)
... 12 more
com.github.lucadruda.iotc.device.exceptions.IoTCentralException: Registration error, bailing out
at com.github.lucadruda.iotc.device.DeviceProvision._internalRegister(DeviceProvision.java:138)
at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:99)
at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:73)
at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:159)
at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:153)
at com.orangelabs.iot.azure.central.IOTAzureCentralTest.utils.DeviceConnUtils.isOpen(DeviceConnUtils.java:60)
at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.reOpenConnection(PushDataThread.java:128)
at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.run(PushDataThread.java:55)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Every device's ID is unique, and the network was ok

**Comment by ynjacobs** [comment]
@lucadruda thanks so much for this library.

@wuwei3 did you include model Id? I got a similar error to yours and when I included the model Id the error seems to go away.

I found model Id in Device Templates -> View Identity -> Interface @Id

**Comment by lucadruda** [comment]
@ynjacobs Thanks!
The answer is correct. 
Provision a new device (not yet registered in IoTCentral) gives back an error even if registration request succeeds on Azure Device Provisioning Service (DPS). That's because this library expects the device to be associated with a template.
However it only applies to device connection with group key.
If devices are already registered in IoTCentral ("registered" state, not "provisioned") and correctly associated with a template, when connection is made through device key, it should not fail.
